version: '3'
services:
  judgement-app:
    build: .
    container_name: judgement-app
    ports:
      - "8080:8080"
    environment:
      # Connect Spring Boot to MongoDB
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=user
      - SPRING_DATA_MONGODB_PASSWORD=pass
      # Other environment variables as needed
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./data:/data/db
